import type { BallColor } from "@pooldawgs/engine";

/**
 * Visual skin: the engine plays UK-style red/yellow groups (faithful port of
 * the forked rules), but the design brief shows classic numbered balls. We
 * render the yellow group as SOLIDS 1–7 and the red group as STRIPES 9–15,
 * with the black as the 8 — rules unchanged, look matches the mockup.
 */
export interface BallStyle {
  number: number | null; // null = cue ball
  kind: "solid" | "stripe" | "eight" | "cue";
  color: string;
}

/** Classic pool palette by ball number (stripe n shares the hue of n−8). */
const NUMBER_COLORS: Record<number, string> = {
  1: "#f0b90b",
  2: "#1f4fd8",
  3: "#d2122e",
  4: "#6a2c91",
  5: "#ef7d14",
  6: "#0f7a3d",
  7: "#7a1f2b",
  8: "#101014",
};

// Rack array order from the engine (ids 0–14, cue = 15):
// yellow ids [0,1,5,6,8,12,14] → solids 1–7
// red ids    [2,3,7,9,10,11,13] → stripes 9–15
const ID_TO_NUMBER: Record<number, number> = {
  0: 1, 1: 2, 5: 3, 6: 4, 8: 5, 12: 6, 14: 7,
  4: 8,
  2: 9, 3: 10, 7: 11, 9: 12, 10: 13, 11: 14, 13: 15,
};

export function ballStyle(id: number): BallStyle {
  if (id === 15) return { number: null, kind: "cue", color: "#f5efe0" };
  const number = ID_TO_NUMBER[id];
  if (number === 8) return { number: 8, kind: "eight", color: NUMBER_COLORS[8] };
  if (number <= 7) return { number, kind: "solid", color: NUMBER_COLORS[number] };
  return { number, kind: "stripe", color: NUMBER_COLORS[number - 8] };
}

/** Ball numbers belonging to an engine group, for the HUD trackers. */
export function groupNumbers(group: BallColor | null): number[] {
  if (group === "yellow") return [1, 2, 3, 4, 5, 6, 7];
  if (group === "red") return [9, 10, 11, 12, 13, 14, 15];
  return [];
}

/** Engine ball ids belonging to a group, in tracker display order. */
export function groupBallIds(group: BallColor | null): number[] {
  if (group === "yellow") return [0, 1, 5, 6, 8, 12, 14];
  if (group === "red") return [2, 3, 7, 9, 10, 11, 13];
  return [];
}

export function numberColor(n: number): string {
  return NUMBER_COLORS[n <= 8 ? n : n - 8];
}

/** SVG asset for an engine ball id (generated by scripts/gen-balls.mjs). */
export function ballAssetPath(id: number): string {
  const style = ballStyle(id);
  return style.number === null
    ? "/assets/balls/ball-cue.svg"
    : `/assets/balls/ball-${style.number}.svg`;
}

/** SVG asset by ball number (for HUD trackers). */
export function ballAssetByNumber(n: number): string {
  return `/assets/balls/ball-${n}.svg`;
}
